Core 1134 - Set last folder, default output folder and notify param in app launch from preferences.
cyverse-de/sonora pull request #185
Opened 2020-09-24 20:28 UTC by sri2k1us

- SSIA

2020-09-24 22:05 UTC, psarando requested changes
Very nice 🎉 
Looks good, except I think we need to get the user's home path from the bootstrap response, then this will be good to :shipit:  👍

2020-09-25 12:52 UTC, sri2k1us commented on src/components/apps/launch/index.js
>          irodsHomePath && username ? `${irodsHomePath}/${username}` : "";
oops missed that one. Yes, that should come from bootstrap.

2020-09-25 18:38 UTC, psarando approved these changes

2020-09-25 18:45 UTC, sri2k1us commented
Thanks for the review.

2020-09-25 18:46 UTC, merged