Bag fixes
cyverse-de/sonora pull request #206
Opened 2020-10-16 18:10 UTC by johnworth

Various fixes for the bag feature that couldn't make it into the first PR without endangering its inclusion in the user testing period.

2020-10-20 23:38 UTC, ash3rz approved these changes
LGTM :shipit:

2020-10-20 23:38 UTC, ash3rz commented on src/components/Bag/downloads/index.js
> +        navigator.clipboard
For anyone else, I was curious about the difference between the copy method we're using [here](https://github.com/cyverse-de/ui-lib/blob/master/src/components/copy/clipboardFunctions.js) vs. this one.  Seems it's totally up to you which way you want to go with according to [this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard)

2020-10-21 17:17 UTC, sri2k1us requested changes
Looks good but I found couple of nagging issues.
1. I don't see a `Share` button anymore when I add file(s) I own. Seems to work right in `prod` though.
![image](https://user-images.githubusercontent.com/1250790/96754509-052ed980-13ef-11eb-8c2b-c17066db097f.png)

2. Icon for `Clear` should match what it is mobile version. 
i.e It should be `import ClearAllIcon from '@material-ui/icons/ClearAll';`

3. Rename Bag folder to lowercase `bag`

2021-01-11 14:51 UTC, johnworth commented
This is old and out of date. I don't even remember working on it at this point. 😄 

Closing this out for now.

2021-01-11 14:51 UTC, closed without merging