Update SB, Next, i18next
cyverse-de/sonora pull request #219
Opened 2020-11-05 17:11 UTC by sri2k1us

SSIA.
I followed https://storybook.js.org/blog/storybook-6-migration-guide/ and https://storybook.js.org/docs/react/get-started/setup for storybook migration.

I strongly suggest checking out this PR locally and trying it to make sure I haven't missed anything. Thanks.

2020-11-05 22:36 UTC, ash3rz approved these changes
LGTM :shipit: 
Code looks good! Went through Storybook and only found the app listing had an issue loading the story (not sure if related to this PR or not).  And went through dev mode, clicked through all the pages, and didn't see any issues.

2020-11-06 14:21 UTC, sri2k1us commented
> LGTM :shipit:
> Code looks good! Went through Storybook and only found the app listing had an issue loading the story (not sure if related to this PR or not). And went through dev mode, clicked through all the pages, and didn't see any issues.

Will take a look

2020-11-06 14:48 UTC, sri2k1us commented
> > LGTM :shipit:
> > Code looks good! Went through Storybook and only found the app listing had an issue loading the story (not sure if related to this PR or not). And went through dev mode, clicked through all the pages, and didn't see any issues.
> 
> Will take a look

Weird..it works for me 😕

![image](https://user-images.githubusercontent.com/1250790/98379402-417c4f80-2015-11eb-8a4d-ee2de6683e54.png)

2020-11-06 19:28 UTC, psarando requested changes
I like the new way to organize stories and adding `argTypes` to the default export for controls.

But it looks like we have to refine our story organization for this upgrade, in order to get rid of `Duplicate title` warnings and attach controls to the right stories.

2020-11-06 19:28 UTC, psarando commented on stories/apps/launch/LoadingError.stories.js
> +        customMessage: {
```suggestion
        "Longer Error Message": {
```

2020-11-06 19:28 UTC, psarando commented on stories/apps/launch/LoadingError.stories.js
> +export const LoadingError = ({ customMessage }) => {
```suggestion
export const LoadingError = ({ "Longer Error Message": customMessage }) => {
```

2020-11-09 15:55 UTC, sri2k1us commented on stories/apps/launch/LoadingError.stories.js
> +};
Removing title from the `export` throws an error in SB. I was able re-organize stories in hierarchical fashion by giving unique names to each story. For example, all stories under `/stories/apps/launch` will have titles with this pattern `Apps / Launch / <current story>`. 
![image](https://user-images.githubusercontent.com/1250790/98564222-19415a80-227a-11eb-8d54-414727fe0035.png)

2020-11-09 15:57 UTC, sri2k1us commented on .storybook/preview.js
> -addDecorator((storyFn, context) => withConsole()(storyFn)(context));
Good Catch. Added back the `console` add-on.

2020-11-09 23:09 UTC, psarando commented on stories/apps/launch/LoadingError.stories.js
> +};
I tried it out in my local copy of this PR, and I also see the error when only removing the `title` from the default exports in these stories.

I think I preferred the old hierarchy, though. This new hierarchy means a lot of extra clicks to navigate and browse from one story to the next.

So in order to preserve the original organization, [we can re-export stories in 1 index file that defines the title](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-support-for-duplicate-kinds), then delete all other default exports from the re-exported stories.

Using the stories under `stories/apps/launch` as an example, a `stories/apps/launch/index.stories.js` file can be created like this:
```javascript
export * from "./AgaveWordCount.stories";
export * from "./DeprecatedParamsApp.stories";
export * from "./DEWordCount.stories";
export * from "./FlagParams.stories";
export * from "./InputParams.stories";
export * from "./JupyterLabNoParams.stories";
export * from "./LoadingError.stories";
export * from "./LoadingMask.stories";
export * from "./NumberParams.stories";
export * from "./OutputParams.stories";
export * from "./Pipeline.stories";
export * from "./ReferenceGenomeParams.stories";
export * from "./SelectParams.stories";
export * from "./TextParams.stories";

export default { title: "Apps / Launch" };
```
Then in each of the original story files the `export default { title: "Apps / Launch" };` line will have to be deleted.

For the stories that use controls, the `export default` can be replaced with `<StoryName>.argTypes = {...}` as described here: https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#knobs-to-manually-configured-args

For example, this `LoadingError` story's default export would be replaced with this:
```javascript
LoadingError.argTypes = {
    customMessage: {
        control: {
            type: "boolean",
        },
    },
};
```

2020-11-10 15:10 UTC, sri2k1us commented on stories/apps/launch/LoadingError.stories.js
> +};
![image](https://user-images.githubusercontent.com/1250790/98691451-0c853b00-233c-11eb-9433-a5b592d29514.png)
Adding current SB screenshot for comparison. 
It requires the same number of clicks (3 or just 2 in most cases) to access, for example `App / Launch / Loading Error`. Please remember, you don't have to expand the `App / Launch / Loading Error` to load that story, simply clicking on the parent node will load that story.
Anyway, the spirt of the PR is to update the version of the software library without introducing new issues / bugs. I think that is achieved.

2020-11-10 18:07 UTC, psarando commented on stories/apps/launch/LoadingError.stories.js
> +};
👌 fair enough.
I also forgot about the auto-selection when expanding a leaf-category.

2020-11-10 18:08 UTC, psarando approved these changes

2020-11-10 18:30 UTC, merged