Fix browser navigation for data view.
cyverse-de/sonora pull request #257
Opened 2020-12-17 21:15 UTC by sri2k1us

- I eliminated props to state copy of `order`, `orderBy`, `page` and `rowsPerPage`. That seems have fixed most of the issues that we have seen so far with respect to browser `Back` and `Forward` buttons based navigation in Data View. We might want to do the same for other views as well.
- Request reviewers to test these changes locally to make sure edges aren't missed.

2020-12-17 21:55 UTC, psarando requested changes
LGTM, except in local testing, changing the page size from 100 to 500 doesn't seem to do anything to the page, and I'm not sure why yet 😕 

If I view the "Shared with Me" listing that has 2 pages at 100 items per page, changing to 500 items per page does change the URL query param to `selectedRowsPerPage=500`, but the listing still displays 2 pages and 100 per page. Navigating to page 2 resets the URL query param to `selectedRowsPerPage=100`.

2020-12-17 22:33 UTC, sri2k1us commented
> LGTM, except in local testing, changing the page size from 100 to 500 doesn't seem to do anything to the page, and I'm not sure why yet 😕
> 
> If I view the "Shared with Me" listing that has 2 pages at 100 items per page, changing to 500 items per page does change the URL query param to `selectedRowsPerPage=500`, but the listing still displays 2 pages and 100 per page. Navigating to page 2 resets the URL query param to `selectedRowsPerPage=100`.

Ok.let me check tomorrow

2020-12-18 17:13 UTC, ash3rz approved these changes
LGTM after the one line fix 👍 tested locally

2020-12-18 19:00 UTC, psarando approved these changes
LGTM 🎉 
Tested locally and didn't catch any more issues 👍 
:shipit:

2020-12-18 19:08 UTC, sri2k1us commented
Thanks for the reviews.

2020-12-18 19:08 UTC, merged