CORE-1485 Rename Quick Launch to Saved Launch
cyverse-de/sonora pull request #403
Opened 2021-08-17 18:19 UTC by ash3rz

To be honest, before this ticket I completely forgot we had 2 types of launches (quick and instant) and I found myself getting confused on which was which. So I renamed everything instead of only updating the display text.

* I also removed some files related to AppTile which wasn't in use
* Removed some i18n strings that weren't actually being used
* I did NOT rename the quick launches URL
* I left server side code completely alone

2021-08-17 18:20 UTC, ash3rz commented on public/static/locales/en/launch.json
> +    "saveAsSavedLaunch": "Save as Saved Launch",
This one and the one above sound a little strange.  Not sure if `Create as Saved Launch` or just `Save Launch` might be better?

2021-08-19 20:40 UTC, sri2k1us approved these changes
LGTM. I have couple of suggestions but we can also discuss that in a UX meeting.

2021-08-19 23:24 UTC, psarando requested changes
Looking good 👍 

I agree with changing the app launch step label to just "Launch or Save".

I also really think we should only be providing links with the `saved-launch-id` query param, since I consider these links as also user-facing, and we can still accept both `quick` and `saved` in the launch page.

2021-08-20 00:15 UTC, ash3rz commented on public/static/locales/en/launch.json
> +    "saveAsSavedLaunch": "Save as Saved Launch",
I started to go with `Save`, but then with App Launch that looked a little confusing next to `Launch Analysis` on which action I should take next.
![image](https://user-images.githubusercontent.com/8909156/130159210-628f3714-f1c5-43aa-b778-9ea53902c716.png)

I'll go with `Create Saved Launch` for now. `Create` makes it sound like I'm generating something new where `Save` sounds like I'm saving my progress on this form while continuing to work on it.  But I'm still open to ideas on this one.

2021-08-20 01:08 UTC, psarando approved these changes
LGTM 👍

2021-08-20 23:22 UTC, ash3rz commented
Thanks for the reviews!

2021-08-20 23:23 UTC, merged