core-1646 Add overwrite warning to public tools with ability to allow…
cyverse-de/sonora pull request #454
Opened 2022-01-27 20:18 UTC by sri2k1us

… overwrites.

2022-01-28 22:25 UTC, psarando requested changes
I'm requesting changes so that we don't attempt to allow non-admins to overwrite public tools (which is not supported in the API).

I also have a suggestion for improving the display of public apps in the confirmation dialog.

2022-01-31 16:32 UTC, sri2k1us commented on src/serviceFacades/tools.js
> +        endpoint: `/api/tools/${tool.id}?overwrite-public=${overwriteAppsAffectedByTool}`,
Good catch!

2022-01-31 20:01 UTC, sri2k1us commented on src/components/tools/edit/EditTool.js
> +                }
Update to use List:
![image](https://user-images.githubusercontent.com/1250790/151864230-504379b0-4fb0-4bfe-abb2-46f2dbc7b1c2.png)

2022-01-31 20:39 UTC, psarando approved these changes
LGTM 👍

2022-01-31 20:39 UTC, psarando commented on src/components/tools/edit/EditTool.js
> +                console.error(getErrorCode(err));
Missed this last review, but this looks like debug logging that can be removed now.

2022-01-31 20:42 UTC, sri2k1us commented
Thanks for the review.

2022-01-31 20:42 UTC, merged