Core 1870
cyverse-de/sonora pull request #513
Opened 2023-02-15 20:40 UTC by sboleyn

Implement code review from PR #509. Add ErroredListing and SubscriptionEmptyListing stories.

2023-02-15 21:23 UTC, slr71 approved these changes
Looks good! 👍 I didn't catch any issues, but I had a couple of questions about some field labels that I was expecting to be internationalized.

2023-02-15 22:54 UTC, psarando requested changes
Very nice cleanup and refactoring here. ✨ 

LGTM, except I think those labels should use i18n messages.

2023-02-15 22:54 UTC, psarando commented on stories/subscriptions/Listing.stories.js
> +    return <ListingTest isAdminView={isAdminView} />;
👍

2023-02-15 22:54 UTC, psarando commented on src/components/subscriptions/listing/TableView.js
> +                            />
✨

2023-02-15 22:54 UTC, psarando commented on src/components/subscriptions/edit/EditQuotas.js
> +                    <GridLabelValue label="Username">
I think this should use the i18n translations:
```suggestion
                    <GridLabelValue label={t("username")}>
```

2023-02-15 22:54 UTC, psarando commented on src/components/subscriptions/edit/EditQuotas.js
> +                    <GridLabelValue label="Plan Name">
I think this should also use the i18n translations:
```suggestion
                    <GridLabelValue label={t("planName")}>
```

2023-02-16 01:21 UTC, sboleyn commented on src/components/subscriptions/edit/EditQuotas.js
> +                    <GridLabelValue label="Username">
Thank you for catching these!

2023-02-16 01:25 UTC, psarando approved these changes
LGTM :shipit: 👍

2023-02-16 01:32 UTC, merged