fix hardcoded urls
cyverse-de/sonora pull request #536
Opened 2023-05-11 15:28 UTC by mb-wali

2023-05-11 21:49 UTC, psarando requested changes
Looks good, except that we have a pattern of adding the next.js config values to a context, and accessing them from a `useConfig` hook in the client-side (this is actually called in a couple of the components updated in this PR).

For consistency, could you please add these config values to the context's state in `src/pages/_app.js` (similar to the way `LEGACY_DE_URL` is added):
https://github.com/cyverse-de/sonora/blob/2d22d413598db88206fb043af7f2b45b8506248e/src/pages/_app.js#L137-L246

See the `CustomIntercom` component for an example of the `useConfig` hook (but I also added some suggestions on usage in this PR):
https://github.com/cyverse-de/sonora/blob/2d22d413598db88206fb043af7f2b45b8506248e/src/components/layout/CustomIntercom.js#L25-L43

2023-05-11 21:49 UTC, psarando commented on src/components/dashboard/dashboardItem/Banner.js
> +    const cyverse_url = publicRuntimeConfig.CYVERSE_URL;
```suggestion
    const cyverse_url = config?.cyverseUrl;
```

2023-05-11 21:49 UTC, psarando commented on src/components/help/HelpTopics.js
> +import getConfig from "next/config";
```suggestion
import { useConfig } from "contexts/config";
```

2023-05-11 21:49 UTC, psarando commented on src/components/help/HelpTopics.js
> +    const de_faq = publicRuntimeConfig.DE_FAQ;
```suggestion
    const [config] = useConfig();
    const support_email = config?.supportEmail;
    const de_faq = config?.deFaq;
```

2023-05-11 21:49 UTC, psarando commented on src/components/layout/AppBar.js
> +const cyverse_url = publicRuntimeConfig.CYVERSE_URL;
```suggestion
const cyverse_url = config?.cyverseUrl;
```

2023-05-12 12:09 UTC, mb-wali commented
@psarando - Thank you so much for the review and helpful tips, i have push new commit with the changes you have requested. please let me know if that is in order.

2023-05-12 21:55 UTC, psarando approved these changes
Thank you @mb-wali, LGTM 👍

2023-05-12 22:00 UTC, merged